# .rubocop.yml

AllCops:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'lib/rack/influxdb.rb'
    - 'lib/rack/influxdb/configuration.rb'
    - 'lib/rack/influxdb/version.rb'
    - 'rack-influxdb.gemspec'
    - 'spec/**/*.rb'
    - 'spec/rack_influxdb_spec.rb'
    - 'spec/spec_helper.rb'

# Disable specific cops that are not critical
Layout/IndentationWidth:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 20

Style/RedundantBegin:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
