name: Reek CI

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2 

    - name: Install dependencies
      run: bundle install

    - name: Run Reek
      run: bundle exec reek
