name: Run Reek with reviewdog

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  reek_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2'] 

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }} 

      - name: Install dependencies
        run: bundle install 

      - name: Run Reek and report to reviewdog
        uses: reviewdog/action-reek@v1
        with:
          tool_name: reek
          level: warning
          reporter: github-pr-review  # This will leave comments on the pull request
          fail_on_error: false        # Don't block merging on Reek warnings
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
