name: Linters

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.2']  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true  # Automatically handles gem caching

      - name: Install Dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run RuboCop Linter
        run: bundle exec rubocop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
